### ISSUE TITLE
Clear history and state

### ISSUE THREAD

**Issue by dantman** [JannicBeck/undox#1]
I'm working with a "load document", make edits, "save document" model rather than one of "save the history". And I think it's possible a different document could be loaded.

I need some way to clear the history and start over with a new "LOAD" action/state rather than just inserting a new load action as part of the history.

Could this be added to undox?

**Comment by JannicBeck** [comment]
One can simply wrap the undox reducer into a clear history reducer:

```
// the reducer which we want to add undo/redo functionality to
const counter = (state = 0, action) => {
  switch (action.type) {
    case 'INCREMENT':
      return state + 1
    default:
      return state
  }
}

const undoxCounter = undox(counter)

const clearHistoryAction = { type: 'CLEAR_HISTORY' }

const clearHistory = reducer => {
  return (state = reducer(undefined, {}), action) => {
    if (action.type === 'CLEAR_HISTORY') return reducer(undefined, {})
    return reducer(state, action)
  }
}

const undoableCounterWithClearHistory = clearHistory(undoxCounter)
```

I think that this is the more flexible approach, but I see that it might be more convenient to add a undox/clear_history action. Just let me know if this helps.

By the way: clearHistory is a higher order reducer here since it takes a reducer as an argument and wraps it producing a new reducer. This is also how undox is implemented.
This way you could also extend undox and store intermediate states see: https://github.com/JannicBeck/undox/issues/2
