### ISSUE TITLE
Better grouping

### ISSUE THREAD

**Issue by dantman** [JannicBeck/undox#3]
`redux-undo`'s `groupBy` makes more sense than this library's group action.

Say I have a TEXT_CHANGED action and call it on the `input` event as the user types. It wouldn't make sense to dispatch `group([textChanged('a'), textChanged('ab'), textChanged('abc'), textChanged('abcd')])`. It's much more logical that I would dispatch `textChanged(...)` one after each other and then want them to be grouped afterwards.

I do think this would work with `undox`'s model. A similar `groupBy` function to redux-undo would probably work. When a new action is dispatched you would check if the previous action has the same groupBy result as it. If so and the action is a normal action, undox would pop it off and push on a `group([prevAction, newAction])`. If so and action is already a group, then undox would replace it with another group with `newAction` appended to it.

**Comment by JannicBeck** [comment]
Well that is one use case, I don't think we can say if either approach is better based on just one case. There are positives and negatives to both approaches I think. Actually in this case you might want to use the onchange event, so you would only have to dispatch once textChanged('abc'). But I'll try to give some insight why I chose this implementation over redux-undo's groupBy:

With redux-undo's groupBy function you have to specify which actions are grouped beforehand, which I don't like because:
1. There might be situations where you want your actions to be grouped and situations where you don't want them to be grouped. This is not possible with redux-undo's approach. Its either these actions are grouped or they are not grouped.
2. What if you want several groups? E.g. ActionA, ActionB form one group and ActionC, ActionD form one group. This is not possible either.
3. Consider these actions textChanged('a'), textChanged('b'), someNotGroupedAction(), textChanged('c'). Since the non grouped action happened between the grouped actions, it breaks the grouping.
4. Consider ActionA and ActionB are grouped actions and have to be undone together, or it will break our application state since ActionA prepares something for ActionB. What if ActionB is an async action and takes some time? If the user does undo now we get the sequence: ActionA .... Undo ... ActionB. We dispatched ActionA and then did undo ActionA and then our ActionB was ready and we dispatched it. But since ActionB needs ActionB before, our state is not in the correct "state" now as ActionA was undone.

With undox group approach all of these were solved, with the caveat that you have to wait for the actions you want to group to be ready and then dispatch all of them in one group action. I am not quite sure yet how much of a limitation that is, or if it even is one. If you can convince me that this has significant downsides that outweigh the listed benefits above, I will consider a groupBy function. But I don't want to encourage the groupBy approach blindly, as I think it does not behave predictable (see: 3 + 4) and is not as flexible (see: 1+2).

But then again I'm probably skewed, since I implemented this and more use cases might pop up that favour the groupBy approach.

**Comment by dantman** [comment]
> Actually in this case you might want to use the onchange event, so you would only have to dispatch once textChanged('abc').

I thought about that, but there are too many negatives. I don't want to use `change` or debounce the `input` event.

- I lose out on live feedback. My actions are actually actions like `setParams(id, 'label', 'value')` and the dispatch-action-per-input means that as the user types into the "Label: [input]" they see that label show up in what they are editing live. This is a very nice feature.
- I am using redux with react. In other words,
  - `onChange` is actually `input` under the hood, I'd have to bind a change event in a ref (although to be honest I'm working with polymer inputs so I already have to bind to `input` in a ref anyways because of a React limitation)
  - Redux state and React are deeply linked in a tight loop, i.e. In the input event I tell Redux the param has updated, Redux tells React the param has updated, and React tells my component the param has updated, and my component/react tells the input that value has changed. It's actually bad practice for me to not immediately tell React the new value of the input and keep it in sync. (If React were behaving normally, the expected behaviour would actually be for react to overwrite the user input and stop it from changing if I do not tell it the new value as soon as it is input)
  - Because of this way React works it's actually fairly complex to go and decide that instead I want to only dispatch on change and have the input out of sync with redux while typing. I would have to add a new bit of state in my component to store the value as its being edited and I'd have to switch between using the value from redux sometimes and the value from state other times. I'd have to find a pattern for switching to state when the user starts typing and switching back to redux after the `change`. And I'd have to figure out what I'm going to do in the unlikely but possible even that I am in the "user editing" state but something else fires a dispatch that changes the value in redux of what I'm "editing".

I actually came up with a similar conclusion that `groupBy` is useless for what I want, but for a different reason:

- Upon a bit of thought I realized, I don't actually even want `group([textChanged('a'), textChanged('ab'), textChanged('abc'), textChanged('abcd')])` in my history. Users input a lot, and each character they type represents a whole action more complex than that – `{type: '.../SET_PARAM', componentId: 'UUID', name: 'field', value: 'the text'}` for every single character added. I don't want that in my history even as a group. And every action before it is pointless, `group([setParam('a'), setParam('b')])` is functionally equivalent to `setParam('b')` because the second one completely overwrites the data in the previous action and since it's grouped the action isn't available to be undone. Rather than `groupBy` creating groups as I described, I'd rather implement something that purges the superfluous actions rather than wrapping them in a group and keeping them around.
- I actually want the opposite of 3., not only do I want an unrelated edit to break up groups but I actually want to slice these groups by time. i.e. If the user types out "Postal code", thinks for a minute, and then replaces it "`Postal` code" -> "Z`|` code" ... "Zip`|` code". I don't want to group that all into a single `textChanged("Zip code")` group, I'd like to account for the minute delay and instead have a set of separate `textChanged("Postal code"), textChanged("Zip code")` actions so the user can undo to what they typed in a minute ago.
- And lastly I realized, input-by-input/character-by-character undo isn't a bad thing within the first moments after an action, grouping together/purging superfluous actions only matters after a bit of time has passed.

So my answer now is, rather than having `groupBy` I'd actually like to be able to set a timeout and dispatch a "CONSOLIDATE_HISTORY" action of my own that would purge the superfluous actions from the history. Or if I don't chose to use the delay, I'd like to be able to reduce the result of actions so history is consolidated (superfluous actions removed) as actions are dispatched.

How about explicitly supporting custom reducers that act on the history instead of acting on the present state? Then when it comes to issues where users need custom history behaviour, like automatic grouping, clearing history, purging old actions, etc... pretty much any of the features I've requested can be implemented by wrapping undox/ngrx-undoable the way you describe https://github.com/JannicBeck/undox/issues/1#issuecomment-371509738 for clearing state.

I know it's already possible to do this by wrapping the library with a reducer. However both your libraries goes to lengths to say that the history state (`history`, `index`, `past`, `present`, `future`) should not be interacted with directly and instead selectors should be used.
An on top of that, even though undox and ngrx-undoable have such different internal representations the way they work outwardly are so similar that switching from one to the other takes just a minute. All the selector using code is even the same, the only real notable changes are changing what you require and how you get the selectors/reducer.

So what about adding something similar to selectors to both libraries which instead allow a wrapping reducer to interact with the history and mutate it. Without directly modifying `history`, `index`, `past`, `present`, or `future`.

For example `state = appendPastAction(state, action);`, `state = removePastAction(state, getPastActionAtIndex(state, -1));` `state = prependPastAction(slicePastActions(state, 0, 10), initialStateAction(stateAfterTenActions));`. These would mutate `history` and `index` in undox and `past` and `future` in ngrx-undoable.

**Comment by JannicBeck** [comment]
`I know it's already possible to do this by wrapping the library with a reducer. However both your libraries goes to lengths to say that the history state (history, index, past, present, future) should not be interacted with directly and instead selectors should be used.`

Yes exactly and you would use the selectors inside your wrapping reducer to not interact with (past, present, future) directly. E.g. you would do `getPastActions(state)` instead of `state.past`.

You can then let your higher order reducer return something like this:

```
return {
  pastActions: removePastAction(getPastActions(state), action),
  presentState: getPresentState(state),
  futureActions: getFutureActions(state)
};
```
Note that pastActions, presentState, futureActions are now your naming decision, you can name them arbitrarily. If I decide to rename past, present, future internally or change their implementation, it will not break your code since you are using `getPastActions` and not `state.past`.

> So what about adding something similar to selectors to both libraries which instead allow a wrapping reducer to interact with the history and mutate it.

Maybe I'm missing something, but I don't see how this is any different from just wrapping the undo reducer which is a common pattern in redux? Whats the benefit of having another parameter to undoable/undox like: `undoable(reducer, clearHistoryReducer)`

compared to `clearHistoryReducer(undoable(reducer))`

I think adding it as a parameter just confuses people to when it will be called and adds code to the library thats not necessarry.

**Comment by dantman** [comment]
> Note that pastActions, presentState, futureActions are now your naming decision, you can name them arbitrarily. If I decide to rename past, present, future internally or change their implementation, it will not break your code since you are using getPastActions and not state.past.

Sure, but I don't understand how this would work the other way. If I'm modifying the data so my representation of the state is now `{pastActions, presentState, futureActions}` how does undox/ngrx-undoable understand the stored state anymore when I pass state to it?

Also, now if I choose to switch back from ngrx-undoable to undox, I'm forcing the state to have a ngrx-undoable type structure.

> Maybe I'm missing something, but I don't see how this is any different from just wrapping the undo reducer which is a common pattern in redux? Whats the benefit of having another parameter to undoable/undox like: undoable(reducer, clearHistoryReducer)

I think we're on different pages. I'm not suggesting adding a parameter to undox/undoable. I'm suggesting having an API of immutable operations on the action history, which have the same API in both undox and ngrx-undoable, but are agnostic to the format of the state like selectors are agnostic to the state (you use the same selector names in both undox and ngrx-undoable, but under the hood the selectors work with different formats of data `{index, history}` vs `{past, present, future}`). Which can then be used in the higher order reducer.

```js
import {undox, createSelectors} from 'undox';
import {splicePastActions} from 'undox/modifiers';

function reducer() {
	// ...
}

const {getPastActions} = createSelectors(reducer);

function historyReducer = reducer => (state, action) => {
	// When requested remove actions from recent history that are redundant
	// Perhaps dispatched on-blur
	if ( action.type === 'CONSOLIDATE_HISTORY' ) {
		do {
			const past = getPastActions(state);
			if ( isActionRedundantAndWorthGrouping( past[past.length - 2], past[past.length - 1] ) {
				// Remove the redundant action by splicing 1 actions
				// at it's index, with no replacement
				state = splicePastActions(state, past.length - 2, 1);
			} else {
				// No more splicing needed
				break;
			}
		} while ( past.length > 4 );
	}

	{
		const past = getPastActions(state);
		// Automatically purge 100 actions from early state
		// when action list is >= 500
		if ( past.length >= 500 ) {
			const state = getStateFromMyReducerForActions(past.slice(1, 100));
			// Splice 100 actions from right after the undox/INIT
			// and replace them with a "STATE_CHECKPOINT" action
			// that initializes the combined state
			splicePastActions(state, 1, 100, stateCheckpointAction(state));
		}
	}

	return state;
};

export default historyReducer(undox(reducer, initialAction))
```

A single `splicePastActions` might be easier to maintain than a series of multiple mutators for past state (like the `{a,pre}pendPastAction`, `removePastAction`, ...). The function would accept the state and do an immutable splice on the portion of history representing the past, whever that happens to be stored in undox/ngrx-undoable. There would also be an `spliceFutureActions`, which in ngrx-undoable would be an immutable splice over `future` and in undox would be an immutable splice on `history` but offset by `index`.

Unless, now that I think about it, you're instead suggesting I write code where I reset the entire history, decide what past and future actions I want, and then pass those actions, the future actions, and a series of UNDO actions through the reducer until I've rebuilt a brand new state from scratch.

**Comment by JannicBeck** [comment]
Ok I think I understood your case now, but I don't think `splicePastActions`, `spliceFutureActions` is scalable. Why not just do `setFutureActions(newFuture)` `setPastActions(newPast)` where the types of these are  `UndoableAction[] => UndoableState` or `UndoxAction[] => UndoxState` so you could do something like this

```
const past = getPastActions(state)
const newPast = past.slice(past.length - 2, 1)
return setPastActions(newPast)
```
This way you could just use any immutable operation on past/future that you like (in this case slice).

Undox/Undoable would have to recalculate present on setActions of course, which might be tricky if I decide to implement memoization aka intermediate states (see #2).

**Comment by dantman** [comment]
> Undox/Undoable would have to recalculate present on setActions of course, which might be tricky if I decide to implement memoization aka intermediate states (see #2).

I presume you mean given [A1, B1, C1] memoizing things so when you return to [A1, B1] you still have a copy of the state after `A1 -> B1` you can re-use.

How about using Map/WeakMap to store the intermediate states? As long as you store part of the history in the metadata to ensure you don't apply an intermediate state when the action is no longer the same, you should be able to make it work even when setPastActions changes the history as long as it's done immutably with the same instances of action objects for unmodified parts of the history.

For instance with this pesudo code for a memoization map of [A1, B1, C1]:

```js
Map {
	[InitialDataState] => {
		action: A1,
		state: A1.state
	},
	[A1.state] => {
		action: B1,
		state: B1.state,
	},
	[B1.state] => {
		action: C1,
		state: C1.state
	}
}
```

If the history was modified to [A1, B1, C2, D1] you'd traverse the stored data fine InitialDataState -> A1.state -> B1.state.

But when you reach the memoized data for B1.state you'll see that the memoized state is for a C1 action applied to B1.state, but the current history instead has a C2 action. At this point you know you have to discard the rest of the memoized data and start calculating fresh state for C2 and D1.

**Comment by JannicBeck** [comment]
Thats an interesting idea, but it would not work for equal states, since they would overwrite each other in the Map. (e.g. InitialDataState == B1.state, we would add B1.state to the map and therefore overwrite this entry, so we would always fail on the first entry in the map, which would be A1.state now.

I feel like memoization brings more problems to the table than it solves. In 99% of the cases a limit should do the trick, since nobody wants to undo 1000 actions anyway. And if you're doing something really computational expensive in your reducers you might be better off doing the chaching inside your reducer.
